import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen} from 'lucide-react';
import Library from './library';
import './styles.css';
export type CurrentUser={id:string;name:string;email:string;role:string;isAdmin:boolean;canContribute:boolean};
async function post(path:string,payload:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível concluir.');return d;}
function App(){const[user,setUser]=useState<CurrentUser|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[invitation,setInvitation]=useState<{name:string;email:string;kind:string}|null>(null),[inviteToken,setInviteToken]=useState('');
useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));const t=params.get('convite');if(t){setInviteToken(t);post('/api/auth/invitation',{token:t}).then(d=>setInvitation(d.invitation)).catch(e=>setError(e.message)).finally(()=>setLoading(false));history.replaceState(null,'',location.pathname);return}fetch('/api/auth/me',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Não foi possível verificar seu acesso. Recarregue a página.');return r.json()}).then(d=>setUser(d.user)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{let d;if(invitation){if(f.get('password')!==f.get('confirm'))throw new Error('As senhas não coincidem.');d=await post('/api/auth/accept',{token:inviteToken,name:f.get('name'),password:f.get('password')})}else d=await post('/api/auth/login',{email:f.get('email'),password:f.get('password')});setUser(d.user);setInvitation(null);setInviteToken('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.')}finally{setBusy(false)}}
async function logout(){await post('/api/auth/logout',{});setUser(null)}
if(loading)return <div className="auth-shell"><p>Carregando biblioteca…</p></div>;
if(user&&!invitation)return <Library onLogout={logout}/>;
return <main className="auth-shell"><div className="auth-brand"><BookOpen size={36}/><span>unifisio<small>BIBLIOTECA CLÍNICA</small></span></div><section className="auth-card"><div className="eyebrow">ACESSO DOS PROFISSIONAIS</div><h1>{invitation?(invitation.kind==='reset'?'Defina uma nova senha':'Ative seu acesso'):'Entrar na biblioteca'}</h1><p>{invitation?'Seu acesso é individual. Escolha uma senha para usar na biblioteca.':'Use seu e-mail e a senha cadastrada na Unifisio.'}</p>{error&&<div className="form-error" role="alert">{error}</div>}{(!inviteToken||invitation)&&<form className="material-form" onSubmit={submit}>{invitation&&<label>Nome<input name="name" defaultValue={invitation.name} required maxLength={100}/></label>}<label>E-mail<input name="email" type="email" autoComplete="username" defaultValue={invitation?.email||''} readOnly={!!invitation} required maxLength={254}/></label><label>{invitation?'Nova senha':'Senha'}<input name="password" type="password" autoComplete={invitation?'new-password':'current-password'} required minLength={invitation?12:undefined} maxLength={128}/></label>{invitation&&<><small className="muted">Use pelo menos 12 caracteres. Uma frase longa é uma boa opção.</small><label>Confirmar senha<input name="confirm" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label></>}<button className="primary" disabled={busy}>{busy?'Aguarde…':invitation?'Salvar e entrar':'Entrar'}</button></form>}{!invitation&&<div className="auth-help"><strong>Primeiro acesso ou esqueceu a senha?</strong><p>Solicite ao administrador um link de cadastro ou de recuperação.</p>{inviteToken&&<button className="secondary" onClick={()=>{setInviteToken('');setError('')}}>Voltar ao login</button>}</div>}</section><p className="auth-footer">Unifisio · Fisioterapia ortopédica e esportiva</p></main>}
createRoot(document.getElementById('root')!).render(<App/>);
