import {useState} from 'react';
import menus from './nutrition-menus.json';
type Material={id:string;title:string;kind:string;category:string;summary:string;status:string};
export default function NutritionGuides({materials,category,onSelectMaterial}:{materials:Material[];category:string;onSelectMaterial:(id:string)=>void}){
 const [tab,setTab]=useState('adult');
 const available=materials.filter(m=>m.category==='Nutrição e alimentação'&&m.status==='published');
 if(!available.length||!['Todas as áreas','Nutrição e alimentação'].includes(category))return null;
 const selected=available.filter(m=>tab==='literature'?m.kind==='Artigo científico':tab==='menus'?m.id.includes('-menu-'):tab==='athlete'?m.id.endsWith('-protocol-athlete'):m.id.endsWith('-protocol-adult')||m.id.endsWith('-protocol-monitor'));
 return <section className="pathology-hub nutrition-hub" aria-label="Nutrição e alimentação"><h2>Nutrição e alimentação</h2><p>Exemplos de 1.500 kcal, acompanhamento e literatura crítica para adultos, atletas e reabilitação.</p><p className="nutrition-notice">1.500 kcal não é uma meta universal. Os cardápios são educativos e precisam de avaliação nutricional; atletas e recuperação de lesão exigem ajuste individual de energia.</p><div className="path-tabs" aria-label="Conteúdo de nutrição">{[['adult','Adultos e controle de peso'],['athlete','Atletas e reabilitação'],['menus','Cardápios de 1.500 kcal'],['literature','Literatura e qualidade']].map(([value,label])=><button type="button" key={value} aria-pressed={tab===value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{label}</button>)}</div><div className="nutrition-cards">{selected.map(m=><article key={m.id}><span>{m.kind}</span><h3>{m.title}</h3><p>{tab==='literature'?m.summary.split('\n\n')[1]:tab==='menus'?'Porções, calorias, método e limites de uso.':'Avaliação, conduta, reavaliação e encaminhamento.'}</p><button type="button" onClick={()=>onSelectMaterial(m.id)}>Abrir material completo</button>{tab==='menus'&&menus.filter(x=>x.id===m.id).map(menu=><details key={menu.id}><summary>Ver refeições e cálculo energético</summary><p>Total estimado: {menu.totalKcal.toLocaleString('pt-BR',{maximumFractionDigits:1})} kcal · proteína: {menu.proteinGrams.toLocaleString('pt-BR',{maximumFractionDigits:1})} g</p>{menu.meals.map(meal=><div key={meal.name}><h4>{meal.name}</h4><div className="nutrition-table"><table><thead><tr><th>Alimento</th><th>Porção (g)</th><th>kcal estimadas</th></tr></thead><tbody>{meal.foods.map((f,i)=><tr key={i}><td>{f.food}</td><td>{f.grams}</td><td>{(f.grams*f.kcal100/100).toLocaleString('pt-BR',{maximumFractionDigits:1})}</td></tr>)}</tbody></table></div></div>)}<p>Fonte: TACO/NEPA-UNICAMP, 4ª ed., 2011. Peso comestível pronto; aveia seca. Óleo adicional, bebidas e substituições alteram os totais. A adequação nutricional individual precisa ser conferida.</p></details>)}</article>)}</div></section>
}
