import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen } from 'lucide-react';
import data from './pathology-data.json';
type Material={id:string;title:string;category:string;summary:string;reference:string;url:string;status:string};
type Profile=typeof data[number];
type Movement={title:string;steps:string[];dose:string;image?:string};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const movements:Record<string,Movement>={
'muscle-motion':{title:'Mobilidade ativa confortável do segmento lesionado',steps:['Confirme músculo, grau BAMIC e arcos autorizados. Escolha posição apoiada que reduza tensão no foco.','Mova lentamente dentro do arco tolerado, sem buscar alongamento máximo; retorne com controle.','Grau 3/4 ou lesão tendínea: aplicar somente após esclarecer diagnóstico e permissões.'],dose:'Exemplo para lesão parcial liberada: 5–10 movimentos lentos. No grau 4 a dose é individual e depende do plano especializado.'},
'muscle-activation':{title:'Contração submáxima em posição protegida',steps:['O profissional escolhe a posição pelo músculo e local da ruptura; não há uma posição universal.','Quando autorizado, faça contração leve contra resistência estável, sem movimento brusco ou esforço máximo.','Relaxe entre tentativas; interrompa diante de dor aguda ou perda de função. Evolua para resistência dinâmica conforme o protocolo do grau.'],dose:'Exemplo em ruptura parcial liberada: 3–5 contrações de 5–20 segundos com descanso. Grau 4 exige dose e autorização individuais; este exemplo não libera carga.'},
'shoulder-slide':{title:'Deslizamento do braço apoiado na mesa',image:'shoulder-slide',steps:['Sente-se diante de uma mesa firme, pés apoiados. Coloque o antebraço sobre uma toalha na mesa e mantenha o ombro relaxado.','Deslize o braço à frente enquanto inclina o tronco suavemente, mantendo a pelve sentada. Use o apoio para reduzir a exigência muscular.','Pare na amplitude liberada e tolerável; volte lentamente. Não empurre com a outra mão nem force dor intensa ou apreensão.'],dose:'Exemplo: 5–10 movimentos lentos em um bloco curto, 1–2 vezes ao dia se tolerado. A amplitude permitida e a resposta da condição prevalecem.'},
'shoulder-rotation':{title:'Rotação externa com resistência leve',image:'shoulder-rotation',steps:['Prenda um elástico leve em ponto firme na altura do cotovelo. Fique com o ombro exercitado do lado oposto à âncora; a tração deve puxar a mão para dentro.','Mantenha cotovelo junto ao tronco, dobrado aproximadamente 90°, com pequena toalha entre braço e corpo. Punho alinhado.','Gire o antebraço para fora dentro do arco permitido, sem afastar cotovelo nem rodar tronco; retorne controlando. No pós-reparo, só iniciar com autorização para resistência e rotação.'],dose:'Exemplo após liberação: 1–2 séries de 8–12, 2–3 dias/semana; 1–2 minutos de descanso. Progredir carga quando execução e resposta permitem, sem exigir falha.'},
'shoulder-supported':{title:'Movimento assistido com o braço sustentado',steps:['Deitado ou sentado com o membro apoiado, sustente braço e antebraço para não tracionar o ombro.','Com ajuda do profissional ou do outro braço, mova apenas dentro da zona autorizada e confortável, sem alongar nervo ou reparo.','Interrompa diante de apreensão, dor aguda ou alteração sensitiva. No plexo, proteja pele insensível e articulações sem controle.'],dose:'Exemplo se liberado: um bloco de 5 movimentos suaves, com pausas; ajuste à fadiga e proteção. Não transformar ausência de dor em permissão.'},
'assisted-task':{title:'Prática de tarefa com gravidade reduzida',steps:['Escolha tarefa simples, como deslizar a mão sobre a mesa, com braço sustentado.','Ajude somente o necessário; procure participação ativa verificável, sem elevar o ombro por compensação dolorosa.','Em transferência nervosa, a relação entre doador/receptor precisa do treinamento indicado pela equipe. Não extrapolar este exemplo.'],dose:'Blocos breves de tentativas de qualidade, com descanso antes de fadiga que prejudique função. Sem dose universal para desnervação.'},
'ankle-motion':{title:'Dorsiflexão e flexão plantar sem apoio no pé',image:'ankle-motion',steps:['Sente-se com a panturrilha apoiada e o pé livre além da borda do suporte, sem descarregar peso no pé.','Leve o pé suavemente para cima e depois para baixo, mantendo o joelho e a perna apoiados. Evite rotação, inversão/eversão ou amplitude que a lesão proíbe.','Não executar através de gesso, fixador que bloqueia a articulação ou segmento artrodesado. O fisioterapeuta confirma o arco permitido.'],dose:'Exemplo quando o movimento estiver liberado: 5–10 repetições lentas em 1–2 blocos curtos. Esse exercício não autoriza apoio ou retirada da imobilização.'},
'calf-raise':{title:'Elevação bilateral do calcanhar em solo plano',image:'calf-raise',steps:['Só iniciar quando apoio e contração da panturrilha estiverem liberados. Fique em pé junto a bancada firme, mãos disponíveis para equilíbrio.','Com os dois pés no chão, eleve os calcanhares, mantendo antepé apoiado; depois desça devagar até o chão. Não usar degrau nesta versão.','Mantenha carga distribuída conforme a permissão. Na fase sem apoio, este exercício não se aplica. Não substituir liberação por uma tentativa “para ver se dói”.'],dose:'Exemplo após liberação: 1–2 séries de 8–12 em dias alternados, com descanso. Progredir carga, depois versão unilateral quando houver capacidade e permissão.'},
'supported-balance':{title:'Equilíbrio perto de apoio firme',steps:['Após liberar apoio unipodal, fique junto a uma bancada e transfira peso gradualmente para o membro a treinar.','Tire o outro pé do chão por um intervalo tolerável, mantendo mãos prontas para apoio. Não começar por superfície instável.','Se apoio unipodal não é permitido, permaneça na distribuição de carga prescrita; não realize este teste.'],dose:'Exemplo: 2 tentativas de 20–30 segundos, com descanso; ajustar capacidade, fadiga e segurança. O tempo não diagnostica risco nem libera esporte sozinho.'},
'hip-abduction':{title:'Abdução de quadril em pé com apoio',image:'hip-abduction',steps:['Após liberar apoio e movimento, segure uma bancada firme; mantenha tronco confortável e pelve aproximadamente estável.','Mova a perna para o lado em pequena amplitude, sem cruzar a linha média ao retornar. Evite inclinar o tronco para aumentar o alcance.','Na tendinopatia glútea, evite adução/compressão provocativa. Na prótese, respeite restrições e eventual reparo abdutor. A imagem não libera carga.'],dose:'Exemplo: 1–2 séries de 8–12 em dias alternados, inicialmente sem resistência. Aumentar carga e amplitude conforme resposta e permissões.'},
'hip-active':{title:'Movimento ativo de quadril em zona confortável',steps:['Escolha posição estável sentada ou deitada, sem cruzar pernas ou combinar arcos proibidos.','Pratique o movimento necessário à tarefa, como pequena flexão para transferência, dentro da permissão; retorne controlando.','Na prótese, confirme abordagem e precauções; na dor lateral, evite adução sustentada. Não exigir amplitude máxima.'],dose:'Exemplo quando permitido: 5–10 movimentos confortáveis em um bloco curto, acompanhado da tarefa. Não há arco universal para todas as próteses.'},
'wrist-motion':{title:'Extensão ativa de punho com antebraço apoiado',image:'wrist-motion',steps:['Após liberar movimento, sente-se com antebraço apoiado na mesa e palma voltada para baixo. Deixe a mão livre além da borda.','Eleve a mão pelo movimento do punho, mantendo dedos relaxados e antebraço apoiado; retorne lentamente.','Use apenas arco autorizado; não acrescente peso, pressão da outra mão ou apoio corporal nesta etapa.'],dose:'Exemplo: 5–10 movimentos em blocos curtos. Dor/edema persistentes pedem ajuste; resistência e descarga de peso têm liberação separada.'},
'grip':{title:'Preensão leve e progressiva',steps:['Após liberar resistência, apoie antebraço e escolha material macio que permita apertar sem esforço máximo.','Feche a mão de maneira confortável e solte completamente; evite segurar a respiração ou dobrar o punho para compensar.','Aumente resistência gradualmente, observando edema e função dos dedos. Dor desproporcional ou alterações autonômicas precisam de avaliação.'],dose:'Exemplo liberado: 1 série de 8–10 apertos leves com pausa; resistência maior depende de consolidação, capacidade e resposta.'},
'neck-motion':{title:'Rotação cervical ativa confortável',image:'neck-motion',steps:['Sentado com tronco e ombros relaxados, olhe à frente.','Gire a cabeça para um lado na amplitude confortável, sem inclinar ou estender para buscar final de arco; volte e repita do outro lado quando indicado.','Não use as mãos para forçar. Tontura nova, sintomas neurológicos ou dor incomum exigem interrupção e triagem.'],dose:'Exemplo após triagem: 5 movimentos lentos por direção, em blocos curtos conforme tolerância. Não insistir para “destravar”.'},
'neck-isometric':{title:'Contração cervical suave contra a própria mão',steps:['Sentado, apoie a palma na testa e mantenha cabeça em posição confortável.','Faça pressão suave da cabeça contra a mão sem produzir movimento; respire normalmente.','Não fazer esforço máximo nem usar este exercício se sintomas neurológicos, trauma ou condição específica contraindicam.'],dose:'Exemplo: 5 contrações de 3–5 segundos, com descanso. Ajustar intensidade e direção à avaliação, sem perseguir dor ou fadiga elevada.'},
'jaw-motion':{title:'Abertura confortável e controlada da mandíbula',image:'jaw-motion',steps:['Sente-se confortavelmente, sem apertar os dentes; use um espelho se ele ajudar a perceber o movimento.','Abra e feche a boca lentamente em amplitude confortável. Observe o trajeto sem forçar uma correção rígida ou buscar abertura máxima.','Não coloque objetos entre os dentes nem pressione mandíbula com a mão. Bloqueio agudo, luxação ou piora importante exigem avaliação.'],dose:'Exemplo para apresentação avaliada: 5 movimentos lentos em bloco curto. Ajustar à dor e mastigação, sem dose universal para toda DTM.'},
'jaw-control':{title:'Controle mandibular com tarefa de baixa demanda',steps:['Pratique abrir/fechar suavemente ou fala curta, conforme a tarefa limitada.','Mantenha intervalos de relaxamento, sem apertamento voluntário dos dentes e sem insistir em movimento doloroso.','Recupere mastigação gradualmente conforme plano interdisciplinar; não prescrever resistência intensa só para “fortalecer a ATM”.'],dose:'Pequenos blocos tolerados, definidos pela avaliação e resposta. O exercício é de aprendizagem/controle, não teste máximo de força.'},
'lumbar-motion':{title:'Movimento lombar escolhido pela resposta',steps:['Após triagem, escolha um movimento confortável, por exemplo pequena inclinação pélvica deitado com joelhos dobrados ou mobilidade em pé apoiado.','Mova devagar sem exigir uma postura ideal; observe se melhora ou piora a tarefa relevante.','Não impor flexão ou extensão como direção obrigatória. Sintomas neurológicos novos ou piora importante exigem reavaliação.'],dose:'Exemplo: 5–10 movimentos confortáveis em um bloco curto; combinar com atividade e exercício de capacidade, conforme preferência e resposta.'},
'chair-rise':{title:'Sentar e levantar de cadeira firme',image:'chair-rise',steps:['Confirme que carga e flexão necessárias à tarefa são permitidas. Encoste a cadeira na parede e use altura que permita controle; pés apoiados.','Incline o tronco e levante sem impulso; volte a sentar controlando a descida. Use mãos ou cadeira mais alta se necessário.','Não exigir agachamento profundo. Na sutura/reparo ou fratura protegida, substituir esta tarefa até liberação específica.'],dose:'Exemplo após liberação: 1–2 séries de 8–12 em dias alternados; evoluir carga/altura conforme capacidade, mantendo resposta estável.'},
'quad-set':{title:'Ativação do quadríceps dentro da permissão',steps:['Deitado, mantenha perna apoiada na posição permitida, sem puxar ou pressionar sobre reparo.','Contraia suavemente a frente da coxa tentando estender o joelho dentro da zona autorizada; relaxe e repita.','Não acrescentar elevação da perna ou resistência externa por conta própria. No reparo extensor, até contração precisa de autorização específica.'],dose:'Exemplo se liberado: 5–10 contrações de 5 segundos com descanso. Contração leve não equivale automaticamente a exercício seguro para todo reparo.'},
'knee-flexion':{title:'Flexão do joelho por deslizamento do calcanhar',image:'knee',steps:['Deitado, coloque calcanhar sobre superfície que permita deslizar; mantenha pelve apoiada.','Deslize o calcanhar em direção ao glúteo até a amplitude permitida e tolerável; volte devagar. A posição da imagem é exemplo, não meta de ângulo.','Respeite limites de sutura, reparo extensor e outros procedimentos; não forçar bloqueio ou dor aguda.'],dose:'Exemplo quando liberado: 5–10 movimentos lentos em um bloco curto; aumentar amplitude somente dentro da permissão e resposta.'},
'knee-extension':{title:'Extensão do joelho com apoio sob o calcanhar',steps:['Deitado, apoie o calcanhar em uma pequena toalha, deixando joelho sem apoio.','Relaxe em direção à extensão permitida, sem pressionar com mãos ou colocar peso sobre joelho. Não buscar hiperextensão além do objetivo.','Retire ou adapte a posição se provocar dor importante; respeite reparo, órtese e amplitude permitida.'],dose:'Exemplo tolerado e liberado: 2–3 sustentações de 30 segundos. A dose e o posicionamento precisam de ajuste individual.'},
'walking':{title:'Caminhada com progressão pela capacidade',steps:['Meça a tolerância atual e escolha terreno seguro; use auxílio se indicado.','Comece com duração executável, registrando ritmo e resposta. Evite mudar duração, inclinação e velocidade simultaneamente.','Aumente exposição em passos toleráveis e reavalie a tarefa e recuperação. Não impor regra percentual de progressão universal.'],dose:'Exemplo em pessoa apta: bloco de 5–10 minutos ou menor se necessário. Frequência e progressão individualizadas.'},
'protected-motion':{title:'Mobilidade protegida do reparo',steps:['Confira por escrito o arco, o uso de órtese e quem pode realizar o movimento.','Se movimento passivo/assistido estiver liberado, sustente coxa e perna sem tracionar o reparo e fique estritamente no arco autorizado.','Não aplicar a imagem de flexão livre como autorização. Se o arco ou a técnica não estão claros, esclarecer com equipe antes de executar.'],dose:'A dose depende do reparo e plano cirúrgico; este guia não fixa graus ou semanas universais.'},
'protected-activation':{title:'Ativação após autorização do reparo extensor',steps:['Confirme se contração, extensão ativa ou elevação da perna já são permitidas: são permissões diferentes.','Comece somente a tarefa autorizada, com assistência/órtese quando prescritas e sem resistência adicional.','Observe controle e eventual lag quando o teste for permitido; não insistir em repetição com perda de extensão.'],dose:'Definir com a equipe conforme técnica, cicatrização e controle; nenhum teste máximo ou carga automática por semana.'},
'child-play':{title:'Retorno gradual a brincadeira permitida',steps:['Após confirmar diagnóstico e apoio, escolha atividade simples apropriada à idade, com responsável e ambiente seguro.','Comece com marcha ou brincar leve na permissão; não iniciar saltos, corrida ou teste provocativo se a lesão ainda exige proteção.','Observe apoio, dor e comportamento no dia seguinte; dor focal persistente ou regressão requerem nova avaliação.'],dose:'Blocos curtos definidos pela tolerância e idade. Não copiar séries/cargas de adultos.'},
'diagnosis-first':{title:'Esclarecer diagnóstico antes de aplicar um exercício',steps:['Confirme tecido e sistema de classificação no laudo e na avaliação.','Investigue integridade do mecanismo extensor, localização e eventual reparo.','Escolha o protocolo correspondente somente depois disso; este rótulo não sustenta técnica, dose ou prazo específicos.'],dose:'Sem dose estabelecida para o rótulo isolado “3B”.'}
};
const tabs=['Visão geral','Avaliação e testes','Dor e educação','Mobilidade','Força e controle','Terapia manual','Pós-operatório','Retorno ao esporte','Prevenção','Referências'];
function splitSections(summary:string){return summary.split(/\n\s*\n/).map(block=>{const [first,...rest]=block.split('\n');return {title:rest.length?first:'Observação',text:rest.length?rest.join('\n'):first};});}
const sectionPatterns:Record<string,RegExp>={
'Visão geral':/ESCOPO|FUNDAMENTO|EVIDENCIA|BASE|QUALIDADE|CERTEZA|RESULTADO|LIMITACO/,
'Avaliação e testes':/AVALIAC|REGISTRO|TRILHAS/,
'Dor e educação':/EDUCAC|PROTECAO|ETAPA 1|FASE 1|PARTICIPAC|TOLERANC/,
'Mobilidade':/MOBIL|ETAPA 1|FASE 1|RESTAURAC/,
'Força e controle':/FORCA|ETAPA 2|FASE 2|RESIST|CAPACIDADE/,
'Pós-operatório':/TRILHA|PROTECAO|ETAPA 1|FASE 1|RESTRIC/,
'Retorno ao esporte':/RETORNO|ETAPA 3|ETAPA 4|FASE 3|DEMANDA|ALTA|PROGRESSAO/,
'Prevenção':/PREVEN|SEGURANCA|CRITERIOS|REAVALIAC/
};
function SourceSections({sources,tab}:{sources:Material[];tab:string}){const pattern=sectionPatterns[tab];const sections=sources.slice(0,1).flatMap(m=>splitSections(m.summary)).filter(s=>pattern?.test(normalize(s.title).toUpperCase())).slice(0,5);return sections.length?<div className="path-source"><h4>Aplicação e critérios do protocolo no acervo</h4>{sections.map((s,i)=><details key={s.title+i} open><summary>{s.title}</summary><p>{s.text}</p></details>)}</div>:null;}
function Exercise({id,profile}:{id:string;profile:Profile}){const m=movements[id];if(!m)return null;const image=m.image==='knee'?'/guides/mobilidade-joelho-fotografica.jpg':m.image?'/guides/'+m.image+'.jpg':null;return <section className="path-exercise"><h4>{m.title}</h4>{image&&<figure><img src={image} alt={'Ilustração de posicionamento: '+m.title+'. A execução e as restrições estão descritas a seguir.'} loading="lazy"/><figcaption>Ilustração gerada por IA · posição exemplificativa, condicionada às permissões de {profile.title.toLowerCase()}.</figcaption></figure>}<ol>{m.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="path-dose"><strong>Dose inicial adaptável</strong><p>{m.dose}</p></div></section>}
function OttawaRules(){return <section className="path-source"><h4>Critérios de Ottawa — pé e tornozelo</h4><p>Triagem para indicar radiografia após trauma agudo. Exige dor na região correspondente e pelo menos um dos critérios abaixo; resultado positivo não confirma fratura.</p><h4>Tornozelo: dor na região dos maléolos + um critério</h4><ul><li>Dor óssea na borda posterior dos 6 cm distais ou ponta do maléolo lateral.</li><li>Dor óssea na borda posterior dos 6 cm distais ou ponta do maléolo medial.</li><li>Incapacidade de dar quatro passos tanto imediatamente após a lesão quanto na avaliação.</li></ul><h4>Pé: dor no mediopé + um critério</h4><ul><li>Dor óssea à palpação na base do 5º metatarso.</li><li>Dor óssea à palpação no navicular.</li><li>Incapacidade de dar quatro passos tanto imediatamente após a lesão quanto na avaliação.</li></ul><p>Um critério basta dentro da região dolorosa. Se ambas as regiões forem positivas, investigar pé e tornozelo. Quatro passos significam transferir peso e caminhar; mancar, por si só, não é incapacidade. Não force a marcha para completar o teste.</p><p className="guide-note"><strong>Fratura por estresse:</strong> Ottawa negativo não exclui lesão por estresse. Dor progressiva sem trauma definido, dor focal e descarga dolorosa exigem investigação própria; a regra não libera corrida, saltos ou tratamento de carga.</p><p>Em crianças e adolescentes, aplicar após trauma quando conseguem comunicar os sintomas claramente e caminhavam normalmente antes da lesão. Avaliação não confiável, deformidade, ferida aberta ou déficit neurovascular exigem avaliação específica, independentemente da regra.</p><p><strong>Registro:</strong> mecanismo e data; região dolorosa; local exato da palpação; quatro passos imediatamente após o trauma e na avaliação; resultado de cada região e encaminhamento.</p><p><a href="https://aci.health.nsw.gov.au/ecat/appendices/ottawa-ankle-adult" target="_blank" rel="noopener noreferrer">Fonte: NSW Health — Ottawa</a> · <a href="https://www.rch.org.au/clinicalguide/guideline_index/fractures/Ankle_Sprains_-_Emergency_Department/" target="_blank" rel="noopener noreferrer">Aplicação pediátrica: Royal Children’s Hospital</a></p></section>}
export default function PathologyGuides({materials,category,objective,onSelectMaterial}:{materials:Material[];category:string;objective:string;onSelectMaterial:(id:string)=>void}){
const [search,setSearch]=useState(''),[selected,setSelected]=useState(''),[tab,setTab]=useState('Visão geral');
const published=materials.filter(m=>m.status==='published');
const profiles=data.filter(p=>p.materialIds.some(id=>published.some(m=>m.id===id)));
const available=profiles.filter(p=>(category==='Todas as áreas'||p.category===category||p.materialIds.some(id=>published.some(m=>m.id===id&&m.category===category)))&&normalize(search).trim().split(/\s+/).filter(Boolean).every(t=>normalize([p.title,p.category,p.restriction].join(' ')).includes(t)));
const profile=profiles.find(p=>p.id===selected);
useEffect(()=>{if(objective==='Todos os objetivos'){setTab('Visão geral')}else if(tabs.includes(objective)){setTab(objective)}},[objective]);
useEffect(()=>{setSelected('')},[category]);
const sources=profile?profile.materialIds.map(id=>published.find(m=>m.id===id)).filter((m):m is Material=>!!m):[];
return <section className="pathology-hub" aria-labelledby="pathology-title"><header className="guide-intro"><div><span className="eyebrow">PROTOCOLOS POR PATOLOGIA</span><h2 id="pathology-title">Encontre a conduta para cada condição</h2><p>Escolha a patologia e abra as abas de avaliação, mobilidade, força e aplicação prática.</p></div><BookOpen aria-hidden="true"/></header>{!profile?<><label className="guide-search">Buscar patologia<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex.: capsulite, Aquiles, Lisfranc, lombalgia"/></label><p className="path-count" role="status">{available.length} guias nesta seleção · {profiles.length} condições no acervo</p><div className="guide-grid">{available.map(p=><button className="guide-card" key={p.id} onClick={()=>{setSelected(p.id);setTab(objective==='Todos os objetivos'?'Visão geral':objective)}}><span>{p.category}</span><h3>{p.title}</h3><small>Abrir guia e aplicação prática <ArrowRight size={14}/></small></button>)}</div>{!available.length&&<p role="status">Nenhum guia nesta seleção. Tente outro termo ou escolha Todas as áreas.</p>}<p className="guide-note">Protocolos e exemplos de execução são específicos à condição. Temas de pesquisa, equipamentos e procedimentos internos continuam no acervo abaixo.</p></>:<article className="path-clinical"><button className="path-back" onClick={()=>setSelected('')}><ArrowLeft size={16}/> Voltar às patologias</button><div className="guide-title"><div><span className="guide-tag">{profile.category}</span><h3>{profile.title}</h3></div></div><p className="guide-scope"><strong>População:</strong> {profile.scope}</p><div className="path-permissions"><strong>Antes de aplicar</strong><p>{profile.restriction}</p></div><div className="path-tabs" role="tablist" aria-label={'Objetivos para '+profile.title}>{tabs.map((t,i)=><button type="button" role="tab" id={'path-tab-'+i} aria-selected={tab===t} aria-controls="path-panel" tabIndex={tab===t?0:-1} key={t} onClick={()=>setTab(t)} onKeyDown={e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[n]);e.currentTarget.parentElement?.querySelector<HTMLButtonElement>('#path-tab-'+n)?.focus();}}>{t}</button>)}</div><div role="tabpanel" id="path-panel" aria-labelledby={'path-tab-'+tabs.indexOf(tab)} className="path-panel" key={profile.id+tab}>
{tab==='Visão geral'&&<><h4>Como utilizar este guia</h4><p>Comece pela avaliação e pelas permissões acima. Escolha o objetivo clínico e combine a aplicação demonstrada com o protocolo da condição. Registre a tarefa, a dose e a resposta.</p><p><strong>Progressão específica:</strong> {profile.progress}</p><p>As doses de aplicação são exemplos clínicos adaptáveis; não são um programa Unifisio validado nem doses ótimas demonstradas. A força da evidência varia por condição e desfecho. Consulte a referência original.</p><SourceSections sources={sources} tab={tab}/></>}
{tab==='Avaliação e testes'&&<>{profile.category==='Tornozelo e pé'&&<OttawaRules/>}<h4>O que medir nesta condição</h4><p>{profile.assessment}</p><ol><li>Escolha uma tarefa relevante e registre sintomas, capacidade e restrições antes da intervenção.</li><li>Padronize instrumento, posição, assistência e descanso. Meça força apenas quando esforço for permitido.</li><li>Reavalie nas mesmas condições; interprete mudança frente ao erro de medida e à relevância para a tarefa. Não use simetria ou um teste isolado como decisão completa.</li></ol><SourceSections sources={sources} tab={tab}/></>}
{tab==='Dor e educação'&&<><h4>Explique o plano e combine a resposta aceitável</h4><ol><li>Pergunte o que a pessoa teme e o que quer voltar a fazer. Relacione a orientação ao diagnóstico: {profile.title.toLowerCase()}.</li><li>Explique as permissões desta condição: {profile.restriction}</li><li>Combine atividade viável e registre sintomas durante, depois e no dia seguinte. Ajuste a dose quando a resposta prejudicar recuperação ou função.</li><li>Não transforme toda dor em dano nem presuma que toda dor é segura. Novos sintomas ou evolução incompatível exigem triagem.</li></ol><SourceSections sources={sources} tab={tab}/></>}
{tab==='Mobilidade'&&<><h4>Como aplicar a mobilidade</h4><p>Identifique a direção limitada e uma tarefa. Os movimentos abaixo só se aplicam quando o arco e o tecido envolvidos estiverem liberados.</p>{profile.mobility.map(id=><Exercise key={id} id={id} profile={profile}/>)}<p><strong>Reavaliar:</strong> repetir amplitude e tarefa, observando dor, derrame/edema e resposta posterior. {profile.progress}</p><SourceSections sources={sources} tab={tab}/></>}
{tab==='Força e controle'&&<><h4>Como aplicar força e controle</h4><p>Escolha entre os exemplos abaixo pela fase e pelo déficit. Eles não formam um circuito obrigatório. Resistência, apoio e amplitude precisam estar liberados separadamente.</p>{profile.strength.map(id=><Exercise key={id} id={id} profile={profile}/>)}<p><strong>Progredir:</strong> quando completar a tarefa com controle e resposta estável, aumentar uma variável por vez. {profile.progress}</p><SourceSections sources={sources} tab={tab}/></>}
{tab==='Terapia manual'&&<><h4>Papel e limites nesta condição</h4><p>{profile.manual}</p><h4>Sequência de aplicação pelo profissional</h4><ol><li>Confirme indicação, contraindicações e consentimento. Registre amplitude/tarefa e sintomas antes do teste.</li><li>Posicione o paciente com o segmento sustentado e músculos relaxados. Escolha contato e direção conforme exame e treinamento; não pressione ferida, foco de fratura ou reparo.</li><li>Faça um teste breve de baixa intensidade, dentro do arco permitido, sem dor crescente ou apreensão. Este guia não autoriza manipulação de alta velocidade, autoaplicação ou técnica intraoral sem habilitação.</li><li>Repita a mesma medida/tarefa. Mantenha apenas se o efeito for relevante e tolerável; combine com prática ativa quando liberada.</li><li>Sem benefício ou com piora, retire a técnica e reveja a hipótese. Não prometer realinhamento, cicatrização acelerada ou superioridade universal.</li></ol><p className="guide-note">A técnica específica e sua dose não podem ser escolhidas só pelo nome da patologia. Quando não há respaldo direto ou permissão, a conduta é não aplicar.</p></>}
{tab==='Pós-operatório'&&<><h4>Confirmar procedimento antes de progredir</h4><p>{profile.restriction}</p><p>Se esta condição estiver em tratamento conservador, a aba não indica necessidade de cirurgia. Se operada, confirmar técnica, procedimentos associados, órtese, apoio, arco e carga permitidos; uma patologia não corresponde a um único procedimento.</p><p>{profile.progress}</p><SourceSections sources={sources} tab={tab}/><p className="guide-note">Na ausência de protocolo cirúrgico correspondente, este guia informa limites e encaminha para plano específico; não inventa um calendário pós-operatório.</p></>}
{tab==='Retorno ao esporte'&&<><h4>Da tarefa básica à demanda real</h4><p>{profile.progress}</p><ol><li>Confirme proteção biológica, estabilidade, amplitude funcional, capacidade de força e confiança para a próxima tarefa.</li><li>Escolha progressão compatível: participação modificada → treino específico → treino completo → competição/desempenho. Trabalho e atividade diária podem ser o objetivo em vez de esporte.</li><li>Treine volume antes de exigir toda intensidade quando apropriado; monitore fadiga, sintomas e função posterior. No trauma/reparo, impacto ou apoio precisam de liberação própria.</li><li>Decisão compartilhada considera capacidade absoluta e exposição representativa. Nenhum prazo ou corte único garante segurança.</li></ol><SourceSections sources={sources} tab={tab}/></>}
{tab==='Prevenção'&&<><h4>Manutenção de capacidade e prevenção de recorrência</h4><p>Continue força e tarefas relevantes quando permitidas, registre adesão e organize carga/recuperação. {profile.progress}</p><p>Identifique fatores modificáveis desta condição sem atribuir risco individual a um teste ou postura isolados. Após fratura, investigar mecanismo e saúde óssea com equipe quando indicado; em tendinopatia, organizar exposição e capacidade.</p><p>A evidência de prevenção é específica da população e da intervenção. Este roteiro de manutenção não demonstra, sozinho, redução de recorrência para {profile.title.toLowerCase()}.</p><SourceSections sources={sources} tab={tab}/></>}
{tab==='Referências'&&<><h4>Fontes e materiais relacionados</h4><p>As referências abaixo pertencem aos registros desta condição. A síntese do acervo mantém método, resultado, aplicabilidade e limitações. Não foram atribuídas classificações próprias de GRADE, RoB 2 ou AMSTAR 2.</p>{sources.map(m=><div className="path-reference" key={m.id}><button className="path-reference-title" onClick={()=>onSelectMaterial(m.id)}>{m.title} <ArrowRight size={14}/></button><p>{m.reference}</p>{m.url&&<a href={m.url} target="_blank" rel="noopener noreferrer">Consultar fonte original <ArrowRight size={14}/></a>}</div>)}{profile.id==='cervical'&&<a href="https://pubmed.ncbi.nlm.nih.gov/40665902/" target="_blank" rel="noopener noreferrer">Diretriz complementar de cervicalgia inespecífica, 2025</a>}<p className="guide-note">Consulta dirigida, outubro de 2026. Os exemplos de execução são adaptações clínicas; não representam cópia integral de um protocolo testado.</p></>}
</div><footer className="path-guide-footer"><span>Unifisio · Guia profissional adaptável</span><button className="secondary" onClick={()=>setTab('Referências')}>Ver referências e protocolo completo</button></footer></article>}</section>
}
