import { useState } from 'react';
import { BookOpen, ArrowRight, Printer } from 'lucide-react';

type Section = { title:string; steps:string[] };
type Guide = { objective:string; title:string; scope:string; evidence:string; sections:Section[]; refs:{label:string;url:string}[] };
const acl={label:'Kotsifaki et al. · Aspetar, 2023 · Diretriz de reabilitação após reconstrução do LCA',url:'https://doi.org/10.1136/bjsports-2022-106158'};
const strength={label:'Currier et al. · ACSM, 2026 · Overview de revisões em adultos saudáveis',url:'https://doi.org/10.1249/MSS.0000000000003897'};
const prevention={label:'Lauersen et al., 2018 · Revisão sistemática e metanálise de ensaios de prevenção',url:'https://pubmed.ncbi.nlm.nih.gov/30131332/'};
export const guides:Guide[]=[
{objective:'Avaliação e testes',title:'Joelho: medir antes de escolher a intervenção',scope:'Roteiro de avaliação funcional para adultos. Escolha testes compatíveis com diagnóstico, fase de recuperação e restrições.',evidence:'A diretriz Aspetar utiliza medidas de sintomas, amplitude, força e função para orientar a progressão após LCA. O roteiro abaixo adapta essa lógica à consulta; não é um escore validado.',sections:[
{title:'1. Defina o objetivo e faça a triagem',steps:['Pergunte qual tarefa está limitada: agachar, descer escadas, correr ou levantar da cadeira. Registre intensidade dos sintomas, derrame, instabilidade e cirurgia recente.','Antes de testar, confirme carga e amplitude permitidas. Febre com joelho quente, bloqueio súbito, trauma com incapacidade de apoiar ou suspeita de trombose exigem avaliação apropriada, em vez de progressão do exercício.']},
{title:'2. Meça amplitude e força de forma repetível',steps:['Goniometria: em decúbito dorsal, alinhe o eixo ao epicôndilo femoral lateral, o braço proximal à coxa e o distal à fíbula. Registre flexão e extensão ativa; acrescente passiva quando indicada. Anote dor, posição e instrumento.','Força: use dinamômetro fixado por cinta, se disponível. Padronize ângulo do joelho, braço de alavanca, estabilização e descanso. Após familiarização, faça três tentativas comparáveis; registre a regra de análise, unidade e dor. Não faça esforço máximo se contraindicado.','Sem dinamômetro, use uma tarefa funcional padronizada (por exemplo, levantar da mesma cadeira). Registre altura, apoio das mãos e repetições. Esse resultado mede desempenho na tarefa e não substitui força máxima isolada.']},
{title:'3. Reavalie e interprete',steps:['Repita a medida com a mesma posição e condições. Compare com a linha de base, a demanda da tarefa e, quando útil, o outro lado.','Uma diferença pequena pode refletir erro de medida. Não declare melhora clinicamente relevante apenas por poucos graus ou uma repetição; considere confiabilidade, sintomas e função.']}
],refs:[acl]},
{objective:'Dor e educação',title:'Dor persistente: educação e retorno gradual à atividade',scope:'Exemplo para lombalgia primária crônica em adultos, após avaliação. Não se aplica automaticamente a dor aguda, radiculopatia ou doença específica.',evidence:'A OMS (2023) inclui educação estruturada e exercício no cuidado da lombalgia primária crônica, dentro de uma abordagem individualizada. Não há uma mensagem ou exercício único para todos.',sections:[
{title:'1. Escute e explique',steps:['Pergunte o que a pessoa entende sobre a dor, o que teme e o que deseja voltar a fazer. Valide sua experiência.','Explique em linguagem simples: dor persistente pode ser influenciada por sensibilidade, sono, estresse e carga, além dos tecidos. Isso não significa que a dor seja imaginária ou que toda dor seja segura. Confirme a compreensão pedindo que a pessoa explique com suas palavras.']},
{title:'2. Construa uma tarefa graduada',steps:['Escolha uma tarefa desejada, como caminhar. Meça o tempo tolerado e combine um começo executável, por exemplo 5–10 minutos se isso for compatível com a capacidade atual.','Combine frequência e registre resposta durante a atividade e no dia seguinte. Aumente primeiro um componente, como duração; ajuste quando os sintomas impedirem a função ou persistirem acima do padrão habitual. A dose é uma proposta de consulta, não uma regra da OMS.']},
{title:'3. Acompanhe função e autonomia',steps:['Associe exercício adaptado, estratégias de autocuidado e metas compartilhadas. Reavalie em 1–2 semanas conforme necessidade clínica.','Use a tarefa e uma escala funcional apropriada para acompanhar progresso. Novos déficits neurológicos, alterações esfincterianas ou sintomas sistêmicos exigem nova triagem.']}
],refs:[{label:'OMS, 2023 · Diretriz para lombalgia primária crônica',url:'https://www.who.int/publications/i/item/9789240081789'}]},
{objective:'Mobilidade',title:'Ganhar mobilidade de joelho: flexão e extensão',scope:'Adultos com limitação de movimento, após identificar a causa. No pós-operatório, respeite os limites do procedimento, do cirurgião e da fase de cicatrização.',evidence:'A diretriz de artroplastia de joelho (APTA, 2026) recomenda exercícios de amplitude. Para artrose de joelho, o NICE (2022) considera terapia manual apenas junto ao exercício. Esses resultados não provam uma técnica ou dose universal para toda rigidez.',sections:[
{title:'1. Avalie e escolha a direção limitada',steps:['Meça flexão e extensão ativa e, se indicada, passiva. Verifique derrame, irritabilidade e qualidade do movimento. Defina uma tarefa: dobrar para sentar ou estender para caminhar.','Distinga limitação por dor/derrame de bloqueio mecânico. Não force bloqueio, dor aguda, articulação inflamada ou restrição cirúrgica. Compare novamente a mesma medida após a intervenção.']},
{title:'2. Flexão: deslizamento do calcanhar',steps:['Posição: deitado de barriga para cima, em superfície firme, com o calcanhar sobre uma toalha para deslizar. Comece com a perna estendida dentro da amplitude permitida.','Execução: deslize o calcanhar em direção ao glúteo, dobrando o joelho e mantendo a pelve apoiada. Pare em tensão tolerável, sem pinçamento ou dor forte, e retorne devagar. Uma faixa no pé pode auxiliar suavemente, sem puxar além do limite.','Exemplo inicial adaptável: 1–2 séries de 8–12 movimentos lentos, com pausa breve de 2–5 segundos no limite tolerado. Uma ou duas sessões curtas por dia se a resposta permitir. A dose é uma proposta prática, não um protocolo universal comprovado.','Progressão: aumente primeiro a amplitude confortável; depois integre flexão em tarefas liberadas, como sentar e levantar. Reduza a dose se houver aumento persistente de dor ou derrame no dia seguinte.']},
{title:'3. Extensão: calcanhar apoiado e quadríceps ativo',steps:['Posição: deitado, coloque uma toalha dobrada sob o calcanhar para deixar o joelho sem apoio. Mantenha pé e joelho alinhados. Não coloque a toalha sob o joelho quando o objetivo for extensão.','Execução: deixe a perna relaxar em direção à extensão permitida, sem empurrar com as mãos nem acrescentar peso. Se tolerado, contraia suavemente o quadríceps, aproximando a parte de trás do joelho da superfície, sem elevar o calcanhar.','Exemplo inicial adaptável: sustentação confortável de 30–60 segundos, repetida 2–3 vezes; contrações de 5 segundos, 5–10 repetições. Ajuste à irritabilidade e às restrições; não busque hiperextensão além do objetivo clínico.','Progressão: priorize extensão ativa e controle na marcha. Ganhar amplitude passiva sem conseguir utilizá-la não resolve sozinho a limitação funcional.']},
{title:'4. Terapia manual: teste de mobilização patelar',steps:['Aplicação exclusiva por fisioterapeuta treinado. Considere apenas quando a avaliação aponta restrição patelar relevante e não há contraindicação. Não use sobre ferida, suspeita de infecção, fratura, instabilidade patelar ou reparo que proíba a técnica.','Posição: paciente deitado, quadríceps relaxado; um pequeno apoio pode manter leve flexão para conforto. Palpe os bordos da patela e examine suavemente sua mobilidade, comparando a resposta.','Contato: apoie a polpa dos dedos nos bordos da patela, sem comprimir diretamente a articulação. Estabilize o membro e produza um pequeno deslizamento na direção restrita. Movimento superior acompanha extensão e inferior acompanha flexão, mas a escolha depende da avaliação; não manipule à força.','Como teste clínico conservador, aplique movimentos suaves por 20–30 segundos, sem dor crescente. Reavalie amplitude e a tarefa. Essa é uma proposta operacional, não uma dose validada nem garantia de ganho.','Mantenha somente se houver benefício relevante e tolerável; depois pratique ativamente a amplitude obtida. Sem benefício, reveja a hipótese. Não atribua melhora automaticamente a “reposicionamento” da articulação.']},
{title:'5. Reavalie a resposta e ajuste',steps:['Registre amplitude, dor, derrame e a tarefa antes/depois, além da resposta no dia seguinte. Aumente um componente por vez; queda funcional ou inflamação persistente pede redução e reavaliação.','Após reconstrução de LCA, sutura meniscal, reparo tendíneo ou artroplastia, as permissões podem diferir. Este guia não libera flexão, apoio ou mobilização por conta própria. Panturrilha dolorosa/inchada, febre ou piora importante exigem avaliação; falta de ar súbita é urgência.']}
],refs:[{label:'Bove et al. · APTA, 2026 · Diretriz de fisioterapia após artroplastia total de joelho',url:'https://doi.org/10.1093/ptj/pzag058'},{label:'NICE NG226, 2022 · Artrose: exercício e terapia manual',url:'https://www.nice.org.uk/guidance/ng226/chapter/Recommendations'},acl]},
{objective:'Força e controle',title:'Força de membros inferiores: do sentar e levantar à carga',scope:'Exemplo para adultos clinicamente estáveis, com exercícios liberados. Ajustar para lesão, cirurgia, comorbidades e experiência de treino.',evidence:'O ACSM (2026), em overview de 137 revisões, sustenta o treino resistido em adultos saudáveis. Cargas altas favorecem força máxima; treinar até falha não é necessário. A aplicação à reabilitação exige adaptação, pois essa população não equivale à dos estudos.',sections:[
{title:'1. Selecione a tarefa e a carga',steps:['Meça a capacidade inicial. Escolha sentar e levantar para iniciante, agachamento para quem já controla a tarefa, extensão do joelho para quadríceps e elevação do calcanhar para panturrilha, conforme indicação.','Escolha carga/amplitude que permita movimento consistente e termine a série com aproximadamente 2–3 repetições ainda possíveis. Não teste 1RM se isso não for adequado à condição clínica.']},
{title:'2. Execute com uma referência clara',steps:['Sentar e levantar: cadeira firme encostada na parede; pés apoiados e afastados confortavelmente. Incline o tronco, levante sem impulso e sente controlando a descida. Use mãos ou cadeira mais alta se necessário; retire ajuda progressivamente.','Agachamento: use apoio se necessário, desça na amplitude tolerada e retorne mantendo controle do tronco e dos membros. Ajuste a estratégia à anatomia e ao objetivo, sem exigir um padrão único de alinhamento.','Extensão de joelho: sentado com coxa apoiada, estenda na amplitude liberada e retorne lentamente. Elevação do calcanhar: com apoio para equilíbrio, suba e desça sem impulso; comece bilateral e progrida quando indicado.']},
{title:'3. Dose e progressão',steps:['Exemplo inicial: 2–3 séries de 8–12 repetições por exercício, 2–3 dias por semana, com 1–3 minutos entre séries e recuperação entre sessões. Use menos volume se a irritabilidade ou a capacidade exigir. Esta é uma adaptação prática, não dose ideal para toda condição.','Quando completar o limite superior com controle e resposta estável, aumente a carga no menor incremento disponível e retorne ao início da faixa. Ajuste carga, volume ou amplitude se houver piora persistente no dia seguinte.','Para força máxima em adultos saudáveis elegíveis, o ACSM favorece cargas de pelo menos 80% de 1RM. Não transfira esse alvo automaticamente para uma fase inicial pós-operatória.']},
{title:'4. Verifique transferência',steps:['Reavalie força e tarefa funcional com o mesmo método. Combine força com equilíbrio, coordenação e exposição à tarefa desejada.','Anote carga, séries, repetições, esforço percebido e resposta. Dor isolada não é o único critério: considere derrame, estabilidade, fadiga e desempenho.']}
],refs:[strength,acl]},
{objective:'Pós-operatório',title:'LCA reconstruído: organizar uma progressão por critérios',scope:'Exemplo específico de reconstrução do LCA. Não é protocolo de sutura meniscal, reparo tendíneo ou artroplastia; procedimentos associados alteram as permissões.',evidence:'Aspetar (2023) coloca exercício no centro da reabilitação após LCA. A progressão deve considerar sintomas, função e restrições, além do tempo biológico. Muitos critérios de progressão ainda têm evidência limitada.',sections:[
{title:'1. Confira o procedimento e as permissões',steps:['Leia relatório cirúrgico: enxerto, procedimentos associados, amplitude permitida, carga, órtese e intercorrências. Se houver conflito, esclareça com a equipe antes de avançar.','Registre dor, derrame, amplitude e capacidade de ativar quadríceps. Observe ferida e sinais que exigem avaliação.']},
{title:'2. Organize a sessão inicial',steps:['Quando liberados, pratique extensão/flexão toleradas, contração do quadríceps e marcha com assistência prescrita. Elevação da perna estendida só quando permitida e sem perda do controle de extensão.','Use sessões breves com resposta monitorada. Escolha dose pela irritabilidade; não determine exercício e amplitude apenas pela semana de cirurgia.']},
{title:'3. Avance força e tarefas',steps:['Progrida exercícios resistidos em cadeia aberta/fechada dentro das permissões, equilíbrio e tarefas funcionais. Dor anterior, aumento de derrame ou perda de amplitude pedem ajuste.','Antes de aumentar demanda, confirme resposta estável, amplitude compatível, controle na tarefa e força suficiente para o próximo desafio. Registre o critério utilizado.']},
{title:'4. Separe recuperação de liberação esportiva',steps:['Correr, saltar e mudar direção precisam de critérios específicos e autorização compatível com o procedimento. Conseguir caminhar sem dor não significa estar pronto para essas tarefas.','Use o guia Retorno ao esporte para planejar a transição. O calendário orienta cicatrização, mas sozinho não determina prontidão.']}
],refs:[acl]},
{objective:'Retorno ao esporte',title:'Após LCA: participação, esporte e desempenho',scope:'Roteiro de decisão compartilhada para atleta após reconstrução do LCA. Requer avaliação individual e integração com equipe médica e esportiva.',evidence:'O consenso de Bern (2016) descreve um contínuo de retorno à participação, ao esporte e ao desempenho. Aspetar (2023) fornece critérios clínicos propostos; não existe uma bateria que garanta ausência de nova lesão.',sections:[
{title:'1. Monte o perfil de prontidão',steps:['Revise dor/derrame, amplitude, força, controle motor, capacidade de correr/saltar e confiança. Considere esporte, posição, nível competitivo e demanda de treino.','Compare força e saltos com o lado contralateral, valores absolutos e demandas do esporte. Simetria isolada pode ocultar fraqueza bilateral; um corte de 90% sozinho não libera o atleta.']},
{title:'2. Exponha em etapas',steps:['Retorno à participação: tarefas e treino modificados. Retorno ao esporte: atividades esportivas progressivamente completas. Retorno ao desempenho: tolerância à exigência do nível desejado.','Exemplo de campo, após cumprir pré-requisitos: corrida linear → aceleração/desaceleração → mudanças de direção planejadas → reativas → treino com oposição. Progrida uma variável por vez, sem percentuais universais de carga.']},
{title:'3. Monitore e compartilhe a decisão',steps:['Registre volume, intensidade, qualidade do movimento, confiança e sintomas no dia seguinte. Se houver derrame, queda de desempenho ou insegurança, ajuste a etapa.','Combine critérios e riscos com atleta, fisioterapeuta, médico e treinador. Inclua prevenção e exposição sustentada a treinos antes da competição.']}
],refs:[{label:'Ardern et al., 2016 · Consenso de Bern sobre retorno ao esporte',url:'https://doi.org/10.1136/bjsports-2016-096278'},acl]},
{objective:'Prevenção',title:'Prevenção no esporte: força e preparação neuromuscular',scope:'Exemplo de rotina para atletas adultos com membros inferiores aptos ao treino. Deve ser adaptada à modalidade e histórico de lesão.',evidence:'Lauersen et al. (2018) encontraram benefício de intervenções de força na prevenção de lesões esportivas. O circuito abaixo é uma adaptação didática, não uma reprodução de um protocolo de ensaio nem garantia de evitar lesões.',sections:[
{title:'1. Comece pela demanda e pela adesão',steps:['Identifique modalidade, calendário, lesões prévias e exercícios já praticados. Selecione demandas relevantes: força, aterrissagem, equilíbrio ou desaceleração.','Reserve uma rotina executável de 15–20 minutos em dois dias da semana, ajustando ao restante do treino. Registre participação e tolerância. Esta duração é um exemplo organizacional.']},
{title:'2. Aplique um circuito inicial',steps:['Aqueça com movimentos progressivos da modalidade. Força: agachamento ou sentar/levantar, ponte de quadril e elevação de panturrilha, por exemplo 2 séries de 8–12 repetições, carga adaptada.','Controle: equilíbrio unipodal perto de apoio, 2 séries de 20–30 segundos por lado. Se saltos estiverem liberados, pratique pequenos saltos bilaterais e aterrissagens controladas, 2 séries de 5; estabilize antes de repetir.','Observe controle e resposta, sem tratar uma aparência de movimento como preditor isolado de lesão. Para modalidades específicas, prefira programas completos estudados e preserve sua progressão e adesão.']},
{title:'3. Progrida sem concentrar fadiga',steps:['Progrida carga de força, tarefa unilateral, velocidade e situações da modalidade conforme capacidade. Não introduza alta carga excêntrica e grande volume de saltos de uma vez.','Ajuste com o treinador para evitar fadiga que prejudique a sessão principal. Monitore sintomas, recuperação, exposição e adesão; prevenção não é um teste único nem uma promessa de risco zero.']}
],refs:[prevention,strength]}
];
function KneeDiagram(){return <div className="knee-diagrams"><figure><svg viewBox="0 0 440 200" role="img" aria-labelledby="flex-title flex-desc"><title id="flex-title">Flexão de joelho com deslizamento do calcanhar</title><desc id="flex-desc">Pessoa deitada. A coxa sobe em direção ao joelho dobrado e o calcanhar desliza pela superfície em direção ao glúteo. A perna pontilhada mostra a posição inicial.</desc><path d="M20 163H420" stroke="#9aaec6" strokeWidth="3"/><circle cx="52" cy="125" r="19" fill="#dce9f8" stroke="#174c85" strokeWidth="3"/><path d="M78 143H190 M190 143L345 143" stroke="#9aaec6" strokeDasharray="7 6" strokeWidth="12" fill="none"/><path d="M78 143H190L260 76L305 145H326" stroke="#174c85" strokeWidth="12" strokeLinecap="round" fill="none"/><circle cx="260" cy="76" r="9" fill="#ec701a"/><path d="M355 178H280l12-8m-12 8 12 8" stroke="#c54b0b" strokeWidth="3" fill="none"/><text x="210" y="32" fill="#174c85" fontSize="16">Dobre sem levantar a pelve</text></svg><figcaption><strong>Flexão</strong> · O calcanhar desliza; a pelve permanece apoiada.</figcaption></figure><figure><svg viewBox="0 0 440 200" role="img" aria-labelledby="ext-title ext-desc"><title id="ext-title">Extensão de joelho com apoio sob o calcanhar</title><desc id="ext-desc">Pessoa deitada com toalha sob o calcanhar e joelho livre de apoio, deixando a perna estender sem peso adicional.</desc><path d="M20 163H420" stroke="#9aaec6" strokeWidth="3"/><circle cx="52" cy="125" r="19" fill="#dce9f8" stroke="#174c85" strokeWidth="3"/><rect x="350" y="136" width="42" height="26" rx="6" fill="#ec701a"/><path d="M78 143H190L265 125L363 127L381 112" stroke="#174c85" strokeWidth="12" strokeLinecap="round" fill="none"/><path d="M265 82v25m-7-8 7 8 7-8" stroke="#c54b0b" strokeWidth="3" fill="none"/><text x="194" y="53" fill="#174c85" fontSize="16">Joelho sem apoio</text><text x="310" y="187" fill="#174c85" fontSize="15">Toalha no calcanhar</text></svg><figcaption><strong>Extensão</strong> · Apoie o calcanhar, sem peso adicional sobre o joelho.</figcaption></figure><p className="diagram-note">Esquemas de posicionamento, sem escala anatômica. A execução e as restrições estão descritas abaixo.</p></div>}
export default function PracticalGuides({objective,onSelect}:{objective:string;onSelect:(value:string)=>void}){
const [term,setTerm]=useState('');
const guide=guides.find(g=>g.objective===objective);
const normal=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const available=guides.filter(g=>normal(term).trim().split(/\s+/).filter(Boolean).every(t=>normal([g.title,g.objective,g.scope,...g.sections.flatMap(s=>s.steps)].join(' ')).includes(t)));
return <section className="practical-guides" aria-label="Guias práticos por objetivo"><div className="guide-intro"><div><span className="eyebrow">DA EVIDÊNCIA À PRÁTICA</span><h2>Guias de aplicação clínica</h2><p>Escolha um objetivo para abrir o passo a passo, a dose e as referências.</p></div><BookOpen aria-hidden="true"/></div>{!guide?<><label className="guide-search">Pesquisar nos guias<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Ex.: joelho, força, LCA, lombalgia"/></label><div className="guide-grid">{available.map(g=><button key={g.objective} className="guide-card" onClick={()=>onSelect(g.objective)}><span>{g.objective}</span><h3>{g.title}</h3><small>Abrir aplicação prática <ArrowRight size={14}/></small></button>)}</div>{!available.length&&<p role="status">Nenhum guia para esse termo. Tente outro objetivo ou região.</p>}<p className="guide-note">Seleção inicial: joelho/LCA, força e prevenção de membros inferiores e lombalgia persistente. Cada guia informa sua população; outras regiões precisam de protocolos específicos.</p></>:<article key={guide.objective} className="clinical-guide"><div className="guide-title"><div><span className="guide-tag">{guide.objective}</span><h3>{guide.title}</h3></div><button className="secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimir guia</button></div><p className="guide-scope"><strong>Para quem:</strong> {guide.scope}</p><div className="evidence-box"><strong>O que sustenta este guia</strong><p>{guide.evidence}</p></div><p className="guide-note">Uso profissional · As doses indicadas como exemplo são adaptações clínicas e precisam de avaliação, consentimento e acompanhamento individual.</p>{guide.objective==='Mobilidade'&&<KneeDiagram/>}<div className="guide-sections">{guide.sections.map(s=><details key={s.title} open><summary>{s.title}</summary><ol>{s.steps.map(step=><li key={step}>{step}</li>)}</ol></details>)}</div><div className="guide-references"><h4>Literatura e limites de aplicação</h4><p>Diretrizes e sínteses apoiam as decisões. Os exemplos de execução não são cópias de protocolos testados.</p>{guide.refs.map(r=><a key={r.url} href={r.url} target="_blank" rel="noopener noreferrer">{r.label} <ArrowRight size={14}/></a>)}<small>Referências conferidas em outubro de 2026.</small></div></article>}</section>
}
