import {useEffect,useState} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {toast} from 'sonner';
const roleLabels:Record<string,string>={admin:'Administrador',professional:'Profissional',reader:'Somente leitura'};
type Person={id:string;name:string;email:string;role:string;active:boolean};
type Invite={id:string;name:string;email:string;role:string;kind:string;expires_at:number};
async function api(path:string,method='GET',payload?:unknown){const r=await fetch(path,{method,headers:payload?{'Content-Type':'application/json'}:undefined,body:payload?JSON.stringify(payload):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível concluir.');return d;}
export default function Professionals({isAdmin,currentId}:{isAdmin:boolean;currentId:string}){const[users,setUsers]=useState<Person[]>([]),[invites,setInvites]=useState<Invite[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[role,setRole]=useState('professional'),[link,setLink]=useState('');
async function load(){try{const d=await api('/api/users');setUsers(d.users);setInvites(d.invites);setError('')}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar.')}finally{setLoading(false)}}
useEffect(()=>{if(isAdmin)void load();else setLoading(false)},[isAdmin]);
async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);try{const d=await api('/api/invites','POST',{email:f.get('email'),name:f.get('name'),role});setLink(d.link);form.reset();toast.success('Convite criado. Copie o link e envie ao profissional.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Falha ao criar convite.')}finally{setBusy(false)}}
async function permissions(u:Person,r:string,active:boolean){setBusy(true);try{await api('/api/users','PATCH',{id:u.id,role:r,active});toast.success('Permissões atualizadas.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Falha ao alterar.')}finally{setBusy(false)}}
async function reset(u:Person){setBusy(true);try{const d=await api('/api/invites','POST',{email:u.email,name:u.name,role:u.role,kind:'reset'});setLink(d.link);toast.success('Link de recuperação criado. Válido por uma hora.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Falha ao criar link.')}finally{setBusy(false)}}
async function revoke(id:string){setBusy(true);try{await api('/api/invites','DELETE',{id});toast.success('Convite revogado.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Falha ao revogar.')}finally{setBusy(false)}}
if(!isAdmin)return <div className="access-guide"><p>Seu acesso é individual. Administradores gerenciam os convites e as permissões da equipe.</p><p><strong>Profissional:</strong> consulta e sugere materiais para revisão.<br/><strong>Somente leitura:</strong> consulta os materiais publicados.</p></div>;
return <div className="professionals"><form onSubmit={create} className="material-form"><h3>Convidar profissional</h3><div className="form-grid"><label>Nome<input name="name" required maxLength={100}/></label><label>E-mail<input name="email" type="email" required maxLength={254}/></label></div><label>Permissão<Select value={role} onValueChange={setRole}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(roleLabels).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label><p className="muted text-sm">O convite vale por 7 dias e permite cadastrar uma senha. Nenhuma mensagem é enviada automaticamente.</p><button className="primary" disabled={busy}>Criar convite</button></form>{link&&<div className="invite-link"><label>Link privado · envie somente ao destinatário<input value={link} readOnly onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);toast.success('Link copiado.')}catch{toast.error('Selecione o link acima e copie.')}}}>Copiar link</button></div>}<h3>Profissionais cadastrados</h3>{loading?<p>Carregando…</p>:error?<p role="alert" className="form-error">{error}<button onClick={()=>void load()}>Tentar novamente</button></p>:users.map(u=><article className="person-row" key={u.id}><div><strong>{u.name}</strong><small>{u.email}</small><span className="status">{u.active?'Ativo':'Suspenso'}</span></div><div className="person-controls"><Select value={u.role} onValueChange={r=>void permissions(u,r,u.active)} disabled={busy||u.id===currentId}><SelectTrigger className="choice" aria-label={'Permissão de '+u.name}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(roleLabels).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select>{u.id!==currentId&&<button className="secondary" disabled={busy} onClick={()=>void permissions(u,u.role,!u.active)}>{u.active?'Suspender':'Reativar'}</button>}{u.active&&<button className="secondary" disabled={busy} onClick={()=>void reset(u)}>Recuperar senha</button>}</div></article>)}{invites.length>0&&<><h3>Links pendentes</h3>{invites.map(i=><div className="invite-row" key={i.id}><div><strong>{i.name}</strong><small>{i.email} · {i.kind==='reset'?'Recuperação':'Convite'}<br/>Expira em {new Date(i.expires_at).toLocaleString('pt-BR')}</small></div><button className="secondary" disabled={busy} onClick={()=>void revoke(i.id)}>Revogar</button></div>)}</>}</div>}
