import {createServer} from 'node:http';
import {readFile,mkdir,writeFile,unlink} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {randomUUID} from 'node:crypto';
import {openDatabase,transaction} from './database.mjs';
import {hashPassword,verifyPassword,token,digest,passwordValid,validEmail,safeString,consumeLimit} from './security.mjs';
import {imageFormat} from './image-format.mjs';
import {categories,kinds} from './catalog.mjs';
const MAX_BODY=16*1024*1024, WEEK=7*86400000;
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const reject=(status,message)=>{throw new HttpError(status,message)};
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:!!u.active,isAdmin:u.role==='admin',canContribute:u.role!=='reader',created_at:u.created_at});
export async function createApp({dataDir,publicUrl,staticDir,secure=true,trustProxy=false}){
 const db=openDatabase(dataDir);const uploads=resolve(dataDir,'uploads');await mkdir(uploads,{recursive:true,mode:0o700});const origin=new URL(publicUrl).origin;const cookieName=secure?'__Host-unifisio':'unifisio_session';const dummyHash=await hashPassword(token());
 function audit(actor,action,subject){db.prepare('INSERT INTO audit(actor_id,action,subject_id,created_at) VALUES(?,?,?,?)').run(actor,action,subject,new Date().toISOString())}
 function cookie(t,clear=false){return `${cookieName}=${clear?'':t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${clear?0:604800}${secure?'; Secure':''}`}
 function user(req){const raw=(req.headers.get('cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!raw)return null;return db.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').get(digest(raw),Date.now())||null;}
 function required(req,admin=false){const u=user(req);if(!u)reject(401,'Entre para acessar.');if(admin&&u.role!=='admin')reject(403,'Somente administradores podem realizar esta ação.');return u;}
 function csrf(req){if(req.headers.get('origin')!==origin)reject(403,'Origem não permitida.');}
 function newSession(u){const t=token();db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(digest(t),u.id,Date.now()+WEEK);return t;}
 function rate(ip,email=''){if(!consumeLimit(db,'ip:'+digest(ip),40,15*60000)||!consumeLimit(db,'email:'+digest(email),12,15*60000))reject(429,'Muitas tentativas. Aguarde 15 minutos e tente novamente.');}
 async function body(req){const n=Number(req.headers.get('content-length')||0);if(n>MAX_BODY)reject(413,'Arquivo muito grande.');try{const data=await req.json();if(!data||typeof data!=='object'||Array.isArray(data))throw 0;return data}catch{reject(400,'Dados inválidos.')}}
 async function handle(req,ip='local'){
 try{const url=new URL(req.url),path=url.pathname,method=req.method;
 if(path==='/health'&&method==='GET'){db.prepare('SELECT 1').get();return json({status:'ok'})}
 if(path.startsWith('/api/')&&method!=='GET'&&method!=='HEAD')csrf(req);
 if(path==='/api/auth/me'&&method==='GET'){const u=user(req);return json({user:u?publicUser(u):null})}
 if(path==='/api/auth/login'&&method==='POST'){const p=await body(req);const email=safeString(p.email,254)?.toLowerCase()||'';rate(ip,email);const password=typeof p.password==='string'&&p.password.length<=128?p.password:'';const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);const valid=await verifyPassword(password,u?.password_hash||dummyHash);if(!valid||!u?.active)reject(401,'E-mail ou senha inválidos.');const t=newSession(u);db.prepare('DELETE FROM auth_limits WHERE key=?').run('email:'+digest(email));audit(u.id,'login',u.id);return json({user:publicUser(u)},200,{'Set-Cookie':cookie(t)})}
 if(path==='/api/auth/logout'&&method==='POST'){const u=user(req);if(u){const raw=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(raw)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(digest(raw));}return json({ok:true},200,{'Set-Cookie':cookie('',true)})}
 if(path==='/api/auth/change-password'&&method==='POST'){const u=required(req);const p=await body(req);rate(ip,u.email);if(!passwordValid(p.password))reject(400,'Use uma senha de 12 a 128 caracteres.');if(typeof p.currentPassword!=='string'||p.currentPassword.length>128||!await verifyPassword(p.currentPassword,u.password_hash))reject(400,'A senha atual não confere.');const encoded=await hashPassword(p.password);transaction(db,()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(encoded,u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);audit(u.id,'password_changed',u.id)});return json({ok:true},200,{'Set-Cookie':cookie(newSession(u))})}
 if(path==='/api/auth/invitation'&&method==='POST'){const p=await body(req);rate(ip,'invitation');if(typeof p.token!=='string'||p.token.length>100)reject(400,'Convite inválido.');const invite=db.prepare('SELECT email,name,kind,expires_at FROM invites WHERE token_hash=? AND used_at IS NULL AND expires_at>?').get(digest(p.token),Date.now());if(!invite)reject(404,'Link inválido ou expirado. Solicite um novo ao administrador.');return json({invitation:invite})}
 if(path==='/api/auth/accept'&&method==='POST'){const p=await body(req);rate(ip,'accept');if(typeof p.token!=='string'||p.token.length>100||!passwordValid(p.password))reject(400,'Confira o link e use uma senha de 12 a 128 caracteres.');const invite=db.prepare('SELECT * FROM invites WHERE token_hash=? AND used_at IS NULL AND expires_at>?').get(digest(p.token),Date.now());if(!invite)reject(400,'Link inválido ou expirado.');const name=safeString(p.name,100);if(!name)reject(400,'Informe seu nome.');const encoded=await hashPassword(p.password);const uid=transaction(db,()=>{const live=db.prepare('SELECT * FROM invites WHERE id=? AND used_at IS NULL AND expires_at>?').get(invite.id,Date.now());if(!live)reject(400,'Esse link já foi usado ou expirou.');let id;if(invite.kind==='reset'){const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(invite.email);if(!u)reject(400,'Conta indisponível.');id=u.id;db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(encoded,id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(id)}else{if(db.prepare('SELECT id FROM users WHERE email=?').get(invite.email))reject(409,'Esta conta já existe.');id=randomUUID();db.prepare('INSERT INTO users(id,email,name,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').run(id,invite.email,name,encoded,invite.role,new Date().toISOString())}db.prepare('UPDATE invites SET used_at=? WHERE id=?').run(Date.now(),invite.id);audit(id,invite.kind==='reset'?'password_reset':'registered',id);return id});const u=db.prepare('SELECT * FROM users WHERE id=?').get(uid);return json({user:publicUser(u)},201,{'Set-Cookie':cookie(newSession(u))})}
 if(path==='/api/users'&&method==='GET'){required(req,true);return json({users:db.prepare('SELECT id,email,name,role,active,created_at FROM users ORDER BY name').all().map(publicUser),invites:db.prepare('SELECT id,email,name,role,kind,expires_at FROM invites WHERE used_at IS NULL AND expires_at>? ORDER BY created_at DESC').all(Date.now())})}
 if(path==='/api/users'&&method==='PATCH'){const actor=required(req,true);const p=await body(req);if(typeof p.id!=='string'||!['admin','professional','reader'].includes(p.role)||typeof p.active!=='boolean')reject(400,'Permissões inválidas.');const current=db.prepare('SELECT * FROM users WHERE id=?').get(p.id);if(!current)reject(404,'Profissional não encontrado.');if(actor.id===p.id&&(p.role!=='admin'||!p.active))reject(400,'Você não pode remover seu próprio acesso de administrador.');transaction(db,()=>{if(current.role==='admin'&&(!p.active||p.role!=='admin')&&db.prepare("SELECT COUNT(*) AS n FROM users WHERE role='admin' AND active=1").get().n<=1)reject(400,'Mantenha pelo menos um administrador ativo.');db.prepare('UPDATE users SET role=?,active=? WHERE id=?').run(p.role,p.active?1:0,p.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(p.id);audit(actor.id,'permissions_updated',p.id)});return json({ok:true})}
 if(path==='/api/invites'&&method==='POST'){const actor=required(req,true);const p=await body(req);const email=safeString(p.email,254)?.toLowerCase(),name=safeString(p.name,100);const role=p.role||'professional',kind=p.kind||'invite';if(!validEmail(email)||!name||!['admin','professional','reader'].includes(role)||!['invite','reset'].includes(kind))reject(400,'Confira nome, e-mail e permissão.');const existing=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(kind==='invite'&&existing)reject(409,'Este profissional já está cadastrado.');if(kind==='reset'&&!existing?.active)reject(400,'Não há uma conta ativa para esse e-mail.');const t=token(),id=randomUUID(),expires=Date.now()+(kind==='reset'?3600000:WEEK);transaction(db,()=>{db.prepare('UPDATE invites SET used_at=? WHERE email=? AND kind=? AND used_at IS NULL').run(Date.now(),email,kind);db.prepare('INSERT INTO invites(id,token_hash,email,name,role,kind,expires_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,digest(t),email,name,existing?.role||role,kind,expires,actor.id,new Date().toISOString());audit(actor.id,kind==='reset'?'reset_link_created':'invite_created',id)});return json({id,link:`${origin}/#convite=${encodeURIComponent(t)}`,expires_at:expires},201)}
 if(path==='/api/invites'&&method==='DELETE'){const actor=required(req,true);const p=await body(req);if(typeof p.id!=='string')reject(400,'Convite inválido.');db.prepare('UPDATE invites SET used_at=? WHERE id=? AND used_at IS NULL').run(Date.now(),p.id);audit(actor.id,'invite_revoked',p.id);return json({ok:true})}
 if(path==='/api/materials'&&method==='GET'){const u=required(req);const rows=u.role==='admin'?db.prepare('SELECT * FROM materials ORDER BY created_at DESC').all():db.prepare("SELECT * FROM materials WHERE status='published' OR author_id=? ORDER BY created_at DESC").all(u.id);return json({materials:rows,user:publicUser(u)})}
 if(path==='/api/materials'&&(method==='POST'||method==='PUT')){const u=required(req);if(u.role==='reader')reject(403,'Seu acesso é de consulta.');const f=await req.formData();const field=(k,max)=>safeString(f.get(k)||'',max);const title=field('title',180),category=field('category',100),kind=field('kind',100),summary=field('summary',20000),reference=field('reference',2000),link=field('url',2000);if(!title||!summary||reference===null||link===null||!categories.includes(category)||!kinds.includes(kind))reject(400,'Confira título, área, tipo e resumo.');if(link){let parsed;try{parsed=new URL(link)}catch{reject(400,'Informe um link válido.')}if(!['http:','https:'].includes(parsed.protocol))reject(400,'Use um link http ou https.');}const id=method==='PUT'?field('id',100):randomUUID(),old=method==='PUT'?db.prepare('SELECT * FROM materials WHERE id=?').get(id):null;if(method==='PUT'&&(!old||(u.role!=='admin'&&(old.author_id!==u.id||!['pending','rejected'].includes(old.status)))))reject(403,'Você não pode editar este material.');const file=f.get('file');let key=old?.file_key||null,name=old?.file_name||null,newKey=null;if(file instanceof File&&file.size){if(file.size>15*1024*1024||file.type!=='application/pdf')reject(400,'Envie um PDF de até 15 MB.');const bytes=Buffer.from(await file.arrayBuffer());if(bytes.subarray(0,5).toString()!=='%PDF-')reject(400,'Arquivo PDF inválido.');newKey=randomUUID()+'.pdf';key=newKey;name=file.name.slice(0,180);await writeFile(resolve(uploads,key),bytes,{mode:0o600,flag:'wx'})}const now=new Date().toISOString(),status=u.role==='admin'?'published':'pending';try{transaction(db,()=>{if(old)db.prepare("UPDATE materials SET title=?,category=?,kind=?,summary=?,reference=?,url=?,file_key=?,file_name=?,status=?,review_note='',updated_at=? WHERE id=?").run(title,category,kind,summary,reference,link,key,name,status,now,id);else db.prepare('INSERT INTO materials(id,title,category,kind,summary,reference,url,file_key,file_name,status,author_id,author_name,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,title,category,kind,summary,reference,link,key,name,status,u.id,u.name,now,now);audit(u.id,old?'material_updated':'material_created',id)})}catch(e){if(newKey)await unlink(resolve(uploads,newKey)).catch(()=>{});throw e}if(newKey&&old?.file_key)await unlink(resolve(uploads,old.file_key)).catch(()=>{});return json({id,status},old?200:201)}
 if(path==='/api/materials'&&method==='PATCH'){const u=required(req,true),p=await body(req);const note=safeString(p.note||'',2000);if(typeof p.id!=='string'||!['published','rejected','archived'].includes(p.status)||note===null)reject(400,'Revisão inválida.');if(p.status==='rejected'&&!note)reject(400,'Inclua uma orientação para o autor.');const r=db.prepare('UPDATE materials SET status=?,review_note=?,updated_at=? WHERE id=?').run(p.status,note,new Date().toISOString(),p.id);if(!r.changes)reject(404,'Material não encontrado.');audit(u.id,'material_'+p.status,p.id);return json({ok:true})}
 if(path.startsWith('/api/files/')&&method==='GET'){const u=required(req),id=path.slice('/api/files/'.length);const row=db.prepare('SELECT * FROM materials WHERE id=?').get(id);if(!row||(!['admin'].includes(u.role)&&row.status!=='published'&&row.author_id!==u.id))reject(404,'Arquivo não encontrado.');if(!row.file_key)reject(404,'Sem arquivo.');const bytes=await readFile(resolve(uploads,row.file_key));return new Response(bytes,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(row.file_name||'material.pdf')}`,'Cache-Control':'private, no-store'}})}
 if(path==='/api/images'&&method==='GET'){const u=required(req);const rows=u.role==='admin'?db.prepare('SELECT * FROM images ORDER BY created_at DESC').all():db.prepare("SELECT * FROM images WHERE (status='published' AND visibility='team') OR author_id=? ORDER BY created_at DESC").all(u.id);return json({images:rows,user:publicUser(u)})}
 if(path==='/api/images'&&(method==='POST'||method==='PUT')){
  const u=required(req);if(u.role==='reader')reject(403,'Seu acesso é de consulta.');const f=await req.formData();const field=(k,max)=>safeString(f.get(k)||'',max);
  const title=field('title',180),category=field('category',100),description=field('description',4000),visibility=field('visibility',20),materialId=field('material_id',100);
  if(!title||!categories.includes(category)||description===null||!['team','restricted'].includes(visibility)||materialId===null)reject(400,'Confira título, área, descrição e acesso.');
  if(materialId){const m=db.prepare('SELECT * FROM materials WHERE id=?').get(materialId);if(!m||(u.role!=='admin'&&m.status!=='published'&&m.author_id!==u.id))reject(400,'Material vinculado indisponível.');}
  const id=method==='PUT'?field('id',100):randomUUID(),old=method==='PUT'?db.prepare('SELECT * FROM images WHERE id=?').get(id):null;
  if(method==='PUT'&&(!old||(u.role!=='admin'&&(old.author_id!==u.id||!['pending','rejected'].includes(old.status)))))reject(403,'Você não pode editar esta imagem.');
  const file=f.get('file');let info=old?{mime:old.mime,width:old.width,height:old.height,size:old.size,key:old.file_key,name:old.file_name}:null,newKey=null;
  if(file instanceof File&&file.size){
   if(file.size>10*1024*1024)reject(413,'Envie uma imagem de até 10 MB.');const bytes=Buffer.from(await file.arrayBuffer());let format;try{format=imageFormat(bytes)}catch(e){reject(400,e.message)}
   const total=db.prepare('SELECT COALESCE(SUM(size),0) AS n FROM images').get().n;if(total-(old?.size||0)+bytes.length>200*1024*1024)reject(413,'A galeria atingiu 200 MB. O administrador pode excluir imagens para liberar espaço.');
   newKey=randomUUID()+'.'+format.ext;info={...format,size:bytes.length,key:newKey,name:(safeString(file.name,180)||'imagem').replace(/[\r\n]/g,'')};await writeFile(resolve(uploads,newKey),bytes,{mode:0o600,flag:'wx'});
  }
  if(!info)reject(400,'Selecione uma imagem JPG, PNG ou WebP.');const now=new Date().toISOString(),status=u.role==='admin'?'published':'pending';
  try{transaction(db,()=>{const total=db.prepare('SELECT COALESCE(SUM(size),0) AS n FROM images').get().n;if(total-(old?.size||0)+info.size>200*1024*1024)reject(413,'A galeria atingiu o limite de 200 MB.');
   if(old)db.prepare("UPDATE images SET title=?,category=?,description=?,material_id=?,visibility=?,status=?,file_key=?,file_name=?,mime=?,size=?,width=?,height=?,updated_at=?,review_note='' WHERE id=?").run(title,category,description,materialId||null,visibility,status,info.key,info.name,info.mime,info.size,info.width,info.height,now,id);
   else db.prepare('INSERT INTO images(id,title,category,description,material_id,visibility,status,file_key,file_name,mime,size,width,height,author_id,author_name,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,title,category,description,materialId||null,visibility,status,info.key,info.name,info.mime,info.size,info.width,info.height,u.id,u.name,now,now);
   audit(u.id,old?'image_updated':'image_created',id);
  })}catch(e){if(newKey)await unlink(resolve(uploads,newKey)).catch(()=>{});throw e}
  if(newKey&&old)await unlink(resolve(uploads,old.file_key)).catch(()=>{});return json({id,status},old?200:201);
 }
 if(path==='/api/images'&&method==='PATCH'){const u=required(req,true),p=await body(req);const note=safeString(p.note||'',2000);if(typeof p.id!=='string'||!['published','rejected','archived'].includes(p.status)||note===null)reject(400,'Revisão inválida.');if(p.status==='rejected'&&!note)reject(400,'Inclua uma orientação para o autor.');const r=db.prepare('UPDATE images SET status=?,review_note=?,updated_at=? WHERE id=?').run(p.status,note,new Date().toISOString(),p.id);if(!r.changes)reject(404,'Imagem não encontrada.');audit(u.id,'image_'+p.status,p.id);return json({ok:true})}
 if(path==='/api/images'&&method==='DELETE'){const u=required(req,true),p=await body(req);if(typeof p.id!=='string')reject(400,'Imagem inválida.');const row=db.prepare('SELECT * FROM images WHERE id=?').get(p.id);if(!row)reject(404,'Imagem não encontrada.');transaction(db,()=>{db.prepare('DELETE FROM images WHERE id=?').run(row.id);audit(u.id,'image_deleted',row.id)});await unlink(resolve(uploads,row.file_key)).catch(()=>{});return json({ok:true})}
 if(path.startsWith('/api/images/')&&path.endsWith('/file')&&method==='GET'){
  const u=required(req),id=path.slice(12,-5);const row=db.prepare('SELECT * FROM images WHERE id=?').get(id);
  if(!row||(u.role!=='admin'&&row.author_id!==u.id&&!(row.status==='published'&&row.visibility==='team')))reject(404,'Imagem não encontrada.');
  const bytes=await readFile(resolve(uploads,row.file_key));return new Response(bytes,{headers:{'Content-Type':row.mime,'Content-Disposition':`${url.searchParams.get('download')==='1'?'attachment':'inline'}; filename*=UTF-8''${encodeURIComponent(row.file_name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
 }
 if(path.startsWith('/api/'))reject(404,'Página não encontrada.');if(method!=='GET'&&method!=='HEAD')reject(405,'Método não permitido.');
 let file;try{const clean=decodeURIComponent(path);file=resolve(staticDir,'.'+clean);if(!file.startsWith(resolve(staticDir)+'/'))file=resolve(staticDir,'index.html');if(extname(file)==='')file=resolve(staticDir,'index.html');const bytes=await readFile(file);const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'}[extname(file)]||'application/octet-stream';return new Response(method==='HEAD'?null:bytes,{headers:{'Content-Type':type,'Cache-Control':extname(file)==='.html'?'no-store':'public, max-age=3600'}})}catch{reject(404,'Página não encontrada.')}
 }catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);if(e instanceof SyntaxError||e instanceof TypeError)return json({error:'Dados inválidos.'},400);console.error('Request failed:',e.message);return json({error:'Não foi possível concluir. Tente novamente.'},503)}}
 const server=createServer(async(nodeReq,nodeRes)=>{try{let n=0;const chunks=[];for await(const chunk of nodeReq){n+=chunk.length;if(n>MAX_BODY){nodeRes.writeHead(413,{'Content-Type':'application/json'});nodeRes.end(JSON.stringify({error:'Arquivo muito grande.'}));return}chunks.push(chunk)}const req=new Request(new URL(nodeReq.url,origin),{method:nodeReq.method,headers:nodeReq.headers,...(['GET','HEAD'].includes(nodeReq.method)?{}:{body:Buffer.concat(chunks)})});const ip=trustProxy?String(nodeReq.headers['x-forwarded-for']||nodeReq.socket.remoteAddress).split(',').at(-1).trim():nodeReq.socket.remoteAddress;const response=await handle(req,ip);const headers=Object.fromEntries(response.headers);headers['X-Content-Type-Options']='nosniff';headers['Referrer-Policy']='no-referrer';headers['X-Frame-Options']='DENY';headers['Content-Security-Policy']="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'";if(secure)headers['Strict-Transport-Security']='max-age=31536000';nodeRes.writeHead(response.status,headers);nodeRes.end(Buffer.from(await response.arrayBuffer()))}catch(e){console.error('HTTP request failed:',e.message);nodeRes.writeHead(500);nodeRes.end('Erro ao processar a solicitação.')}});
 server.headersTimeout=15000;server.requestTimeout=60000;
 const cleanup=setInterval(()=>{try{const now=Date.now();db.prepare('DELETE FROM sessions WHERE expires_at<?').run(now);db.prepare('DELETE FROM auth_limits WHERE reset_at<?').run(now)}catch(e){console.error('Cleanup failed',e.message)}},3600000);cleanup.unref();
 return {server,db,handle,close:()=>{clearInterval(cleanup);db.close()}};
}
